### ISSUE TITLE
Externs failed

### ISSUE THREAD

**Issue by tiensonqin** [tiensonqin/exponent-cljs-template#12]
Jan 05, 2017 11:41:43 AM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /Users/tienson/codes/exponent/template/spurs-om/js/externs.js:1: ERROR - Parse error. Semi-colon expected
var cljs-exponent.components={};
        ^

Jan 05, 2017 11:41:43 AM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 1 error(s), 0 warning(s)
ERROR: JSC_PARSE_ERROR. Parse error. Semi-colon expected at /Users/tienson/codes/exponent/template/spurs-om/js/externs.js line 1 : 8

**Comment by seantempesta** [comment]
Yeah, honestly I never had luck with your extern inference code.  I propose using Clojurescript's new `infer-externs` setting.  It's been working pretty well for me. 

https://clojurescript.org/guides/externs

**Comment by seantempesta** [comment]
I'm closing this issue in favor of clojurescript compilers `:infer-externs` setting.
