### ISSUE TITLE
externs fail on seeing defprotocol

### ISSUE THREAD

**Issue by gmp26** [tiensonqin/exponent-cljs-template#16]
On `externs.js` generation it's throwing
```txt
#object[java.io.File 0x2195f9a7 "src/graphics/scales.cljs"] #error {
 :cause "Can't change/establish root binding of: *unchecked-if* with set"
 :via
 [{:type clojure.lang.ExceptionInfo
   :message "Can't change/establish root binding of: *unchecked-if* with set in file src/graphics/scales.cljs"
   :data {:tag :cljs/analysis-error}
   :at [clojure.core$ex_info invokeStatic "core.clj" 4724]}
  {:type java.lang.IllegalStateException
   :message "Can't change/establish root binding of: *unchecked-if* with set"
   :at [clojure.lang.Var set "Var.java" 221]}]
```
Google this error and you find reference to an old clojurescript REPL problem where the problem was triggered by analysing a `defprotocol` form. I suspect the cause is similar here since `src/graphics/scales.cljs` is the new file in my repo that triggered this problem, and the only one in my app that uses defprotocol, and the stack trace contains this snippet: (edited)

```txt
[cljs.analyzer$analyze invoke "analyzer.cljc" 3061]
[externs$file_ast$fn__21780 invoke "externs.clj" 94]
[clojure.core$mapv$fn__9114 invoke "core.clj" 6785]
[clojure.core.protocols$fn__8889 invokeStatic "protocols.clj" 167]
[clojure.core.protocols$fn__8889 invoke "protocols.clj" 124]
```
I'll keep ferreting around to try and find a minimal case, but thought I'd let you know about the issue. The generated externs.js file ends up with a bad statement on line 1:
```js
var ={};
```

Here is the fix David Nolen applied to the repl.
https://groups.google.com/forum/#!topic/clojurescript/__Qf6L40cwU.

Maybe we need to do something similar in externs.clj?...
See https://github.com/clojure/clojurescript/commit/b2e3a46c57156011932bd84d7aef1b941e01a2f6.

**Comment by gmp26** [comment]
Following above idea, I've added this binding to externs.clj:90
```clojure
ana/*unchecked-if* false
```

This is a partial fix in that there is no longer an exception. However the dodgy `var ={};` is still generated.

**Comment by seantempesta** [comment]
So, I ended up disabling @tiensonqin's extern inference code in favor of Clojurescript's new `:infer-externs`.  Have you tried that?

https://clojurescript.org/guides/externs

```clojure
:prod {:cljsbuild {:builds [{:id           "main"
                                          :source-paths ["src" "env/prod" "../kidlink-server/src/cljc/"]
                                          :compiler     {:output-to          "main.js"
                                                         :source-map         "main.js.map"
                                                         :main               "env.main"
                                                         :output-dir         "target"
                                                         :infer-externs      true
                                                         :parallel-build     true
                                                         :optimize-constants true
                                                         :optimizations      :advanced
                                                         :closure-defines    {"goog.DEBUG" false}}}]}}})
```

**Comment by seantempesta** [comment]
I'm closing this issue in favor of clojurescript compilers `:infer-externs` setting.
