### ISSUE TITLE
Source maps not works on boot template

### ISSUE THREAD

**Issue by tiensonqin** [tiensonqin/exponent-cljs-template#19]

**Comment by seantempesta** [comment]
So, I've never used boot.  If anyone has any experience in this area, please chime in.

**Comment by kennethkalmer** [comment]
I don't know enough about boot either, but I wanna add that this doesn't seem related to exponent. I'm not using exponent, but I've been tearing my hair out with not getting `.cljs` or `.cljc` to show up in Chrome Developer tools. They are generated, I can see them in boot's caches and I can request the URL and get a map in return, but Chrome just shows a blank source panel...

Don't know if this is what @tiensonqin saw, but I thought I'd just help shed some light.

**Comment by seantempesta** [comment]
Closing this for now as boot support has been (hopefully temporarily) deprecated.
