### ISSUE TITLE
Expo's 15.0.0 version changed source-maps location

### ISSUE THREAD

**Issue by seantempesta** [tiensonqin/exponent-cljs-template#20]
Same problem that re-natal had:
https://github.com/drapanjanas/re-natal/commit/cf3afca9c282016e394fcdd7430781e2213f1d8e

old location = `node_modules/react-native/packager/react-packager/src/Server/index.js`
new location = `node_modules/react-native/packager/src/Server/index.js`

```clojure
(defn enable-source-maps
  []
  (println "Source maps enabled.")
  (let [path "node_modules/react-native/packager/src/Server/index.js"]
    (spit path
          (str/replace (slurp path) "/\\.map$/" "/main.map$/"))))
```

**Comment by tiensonqin** [comment]
Thank you for the report, I've fixed it. 
https://github.com/tiensonqin/exponent-cljs-template/commit/e65540c580560bbd3801639d6dd8420e25d23d96
