### ISSUE TITLE
`get-lan-ip` returns my public IP address instead of something which is accessible in my LAN

### ISSUE THREAD

**Issue by ducky427** [tiensonqin/exponent-cljs-template#26]
I am on OS X and I am trying to develop for iOS.

`get-lan-ip` is returning my public IP address instead of something like `192.168.x.x` which is causing the iOS simulator to not see the the figwheel connection.

For me, the IP address returned by the else part of the function works.

**Comment by seantempesta** [comment]
So, I ended up hardcoding the IP I want to use (as sometimes my internet connection drops out and I need to switch to tethering), plus I don't like it when magic is happening and I don't understand what's going on.  

Would you prefer a way to manually specify the IP you want to connect on?

**Comment by seantempesta** [comment]
With my latest commit I changed the behavior to use whatever host is specified in `.expo/settings.json`.  These settings are either modified by hand or with the `XDE` tool.  I feel like this behavior makes more sense than trying to guess your IP and store the value separately than what `expo` is using.

Please let me know your thoughts?

**Comment by seantempesta** [comment]
Added a new feature where you can specify any IP address you want to use for your LAN ip in a `.lan-ip` file.  Please reopen if you still have problems.
