### ISSUE TITLE
Boot build on fresh template fails.

### ISSUE THREAD

**Issue by jarcane** [tiensonqin/exponent-cljs-template#27]
On a fresh boot install, and new template, `boot dev` fails, through the following complaints:

```
Classpath conflict: org.clojure/clojure version 1.7.0 already loaded, NOT loading version 1.9.0-alpha10
```
```
java.lang.RuntimeException: No such var: string/index-of
clojure.lang.ExceptionInfo: No such var: string/index-of
    file: "cljs/source_map.clj"
    line: 268
```

**Comment by tiensonqin** [comment]
@jarcane I think this is because your ~/.boot/boot.properties specified with 
BOOT_CLOJURE_VERSION=1.7.0.

**Comment by jarcane** [comment]
Deleting my own local  ~/.boot/boot.properties, and letting boot infer from the one included in a new template seems to have got it working. I still get a complaint about a classpath conflict, but it builds.
