### ISSUE TITLE
lein prod-build does not seem to work

### ISSUE THREAD

**Issue by robert-johansson** [tiensonqin/exponent-cljs-template#3]
After generating a new project with

`lein new exponent exp3rj +reagent` and `npm install`, I get the following when I run `lein prod-build`:

`Start to generate externs...
#error {
 :cause Invalid token: ::db/app-db
 :data {:type :reader-exception}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message Invalid token: ::db/app-db
   :data {:type :reader-exception}
   :at [clojure.core$ex_info invokeStatic core.clj 4724]}]
 :trace
 [[clojure.core$ex_info invokeStatic core.clj 4724]
  [clojure.core$ex_info invoke core.clj 4724]
  [clojure.tools.reader.reader_types$reader_error invokeStatic reader_types.clj 389]
  [clojure.tools.reader.reader_types$reader_error doInvoke reader_types.clj 385]
  [clojure.lang.RestFn invoke RestFn.java 439]
  [clojure.tools.reader$read_keyword invokeStatic reader.clj 359]
  [clojure.tools.reader$read_keyword invoke reader.clj 345]
  [clojure.tools.reader$read_STAR_ invokeStatic reader.clj 916]
  [clojure.tools.reader$read_STAR_ invoke reader.clj 897]
  [clojure.tools.reader$read_delimited invokeStatic reader.clj 197]
  [clojure.tools.reader$read_delimited invoke reader.clj 190]
  [clojure.tools.reader$read_list invokeStatic reader.clj 210]
  [clojure.tools.reader$read_list invoke reader.clj 206]
  [clojure.tools.reader$read_STAR_ invokeStatic reader.clj 916]
  [clojure.tools.reader$read_STAR_ invoke reader.clj 897]
  [clojure.tools.reader$read_delimited invokeStatic reader.clj 197]
  [clojure.tools.reader$read_delimited invoke reader.clj 190]
  [clojure.tools.reader$read_list invokeStatic reader.clj 210]
  [clojure.tools.reader$read_list invoke reader.clj 206]
  [clojure.tools.reader$read_STAR_ invokeStatic reader.clj 916]
  [clojure.tools.reader$read_STAR_ invoke reader.clj 897]
  [clojure.tools.reader$read_delimited invokeStatic reader.clj 197]
  [clojure.tools.reader$read_delimited invoke reader.clj 190]
  [clojure.tools.reader$read_list invokeStatic reader.clj 210]
  [clojure.tools.reader$read_list invoke reader.clj 206]
  [clojure.tools.reader$read_STAR_ invokeStatic reader.clj 916]
  [clojure.tools.reader$read_STAR_ invoke reader.clj 897]
  [clojure.tools.reader$read_delimited invokeStatic reader.clj 197]
  [clojure.tools.reader$read_delimited invoke reader.clj 190]
  [clojure.tools.reader$read_list invokeStatic reader.clj 210]
  [clojure.tools.reader$read_list invoke reader.clj 206]
  [clojure.tools.reader$read_STAR_ invokeStatic reader.clj 916]
  [clojure.tools.reader$read_STAR_ invoke reader.clj 897]
  [clojure.tools.reader$read invokeStatic reader.clj 966]
  [clojure.tools.reader$read invoke reader.clj 942]
  [externs$read_file$fn__21821 invoke externs.clj 53]
  [clojure.core$repeatedly$fn__7225 invoke core.clj 5052]
  [clojure.lang.LazySeq sval LazySeq.java 40]
  [clojure.lang.LazySeq seq LazySeq.java 49]
  [clojure.lang.RT seq RT.java 525]
  [clojure.core$seq__6172 invokeStatic core.clj 137]
  [clojure.core$take_while$fn__6682 invoke core.clj 2876]
  [clojure.lang.LazySeq sval LazySeq.java 40]
  [clojure.lang.LazySeq seq LazySeq.java 49]
  [clojure.lang.Cons next Cons.java 39]
  [clojure.lang.RT next RT.java 703]
  [clojure.core$next__6156 invokeStatic core.clj 64]
  [clojure.core$dorun invokeStatic core.clj 3114]
  [clojure.core$doall invokeStatic core.clj 3120]
  [clojure.core$doall invoke core.clj 3120]
  [externs$read_file invokeStatic externs.clj 56]
  [externs$read_file invoke externs.clj 46]
  [externs$file_ast invokeStatic externs.clj 72]
  [externs$file_ast invoke externs.clj 61]
  [externs$get_undefined_vars_and_interop_used invokeStatic externs.clj 136]
  [externs$get_undefined_vars_and_interop_used invoke externs.clj 135]
  [clojure.core$pmap$fn__9131$fn__9132 invoke core.clj 6894]
  [clojure.core$binding_conveyor_fn$fn__6522 invoke core.clj 2019]
  [clojure.lang.AFn call AFn.java 18]
  [java.util.concurrent.FutureTask run FutureTask.java 266]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}`

**Comment by tiensonqin** [comment]
@robert-johansson Thank you for reporting.
Could you try latest version?
https://github.com/tiensonqin/exponent-cljs-template/commit/f794c8fd107e2feae56adfe0d4351198b96790f7

Let me know whether it works or not for you.

**Comment by robert-johansson** [comment]
It works great!! Thanks a lot!

**Comment by tiensonqin** [comment]
@robert-johansson Did externs works for you?
