### ISSUE TITLE
yarn.lock file in .gitignore?

### ISSUE THREAD

**Issue by chpill** [tiensonqin/exponent-cljs-template#32]
Hello,

Thanks for this template, it helped tremendously in bootstrapping a mobile app project I'm working on.

I have a question though, why is the yarn.lock file ignored in the default `.gitignore` of the template? 

It allows to deterministically re-install the node_modules (what yarn was designed to do), so it seems really weird not to version it.

**Comment by tiensonqin** [comment]
I actually don't know about this! Thanks for pointing it out, will remove
it tomorrow, not in front of a PC.

**Comment by chpill** [comment]
Thanks!
