### ISSUE TITLE
[exp] Figwheel: trying to open cljs reload socket

### ISSUE THREAD

**Issue by jarcane** [tiensonqin/exponent-cljs-template#34]
If I use this with the mobile app, I constantly get the following message from exp while it's running: 
```
[exp] Figwheel: trying to open cljs reload socket
```
Auto-rebuild is still working, so by and large I can still work with it, but I don't get the Figwheel REPL. It just says "Prompt will show when Figwheel connects to your application" and then never does. It's the same in either boot or lein.

Is it possible to get this working with the Expo app, or, barring that, at least just offer a config to run just the auto-build, and skip Figwheel REPL, to avoid cluttering my exp stdout?

**Comment by myguidingstar** [comment]
I had the same problem. In my case it's the wrong IP address (the one got detected and written to `env/dev/env/dev.cljs`) that caused the problem. My fix was to hardcode the IP address by replacing:
```
;; in function `write-env-dev` from `env/dev/user.clj`
[hostname (.getHostName (java.net.InetAddress/getLocalHost))
 ip (get-lan-ip)]
```
with
```
[hostname (.getHostName (java.net.InetAddress/getLocalHost))
 ip "192.168.0.111"] ;; detected by expo. should change when I reconnect to the network
```
I still need to figure out how to fix that (get-lan-ip) function... In the meantime maybe we should accept an explicit ip address as argument to lein/boot dev command, ie `lein figwheel -i 192.168.0.111` or `boot dev -i 192.168.0.111`.

**Comment by fgui** [comment]
This issue has the same root as #26, 'get-lan-ip' is not getting the correct ip. Pull request #36 is a possible solution.

**Comment by seantempesta** [comment]
So I just changed the ip detection behavior to now use whatever value is stored in `.expo/settings.json`.  I appreciate the pull request, but think it's better to couple this behavior with the expo tools.  What do you think?

https://github.com/seantempesta/expo-cljs-template/commit/47c0a664c472e8b0b5b8089145d15666ce764377

**Comment by seantempesta** [comment]
In addition to searching the expo settings file, you can also override the IP used for figwheel by specifying your IP address in a`.lan-ip` in your project's directory.  Please reopen if this doesn't fix your problem.
