### ISSUE TITLE
Upgrade exponent template for Expo v17

### ISSUE THREAD

**Issue by seantempesta** [tiensonqin/exponent-cljs-template#35]
Saw this was released a few days ago.  

https://blog.expo.io/expo-sdk-v17-0-0-is-now-available-2c4f13362816

Might be a good time to upgrade other dependencies.  Anyone have any preferences for/against this collection?

```clojure
[org.clojure/clojure "1.9.0-alpha16"]
[org.clojure/clojurescript "1.9.542"]
[reagent "0.6.1"]
[re-frame "0.9.3"]
```

Anyone know about upgrading rum and om-next to their latest versions?  I was just planning to use the latest release and test the simple template, but I know that's a bit naive.

**Comment by seantempesta** [comment]
Okay, I've taken my first stab at this with this commit: https://github.com/seantempesta/expo-cljs-template/commit/08d0f865499c25006d9ec91ea4046f19f3419a3d

I know some boot stuff broke due to figwheel issues (`boot-figwheel` isn't being actively maintained?).  The Reagent/Leiningen stuff seems pretty solid.  I'll continue updating this ticket as I make more changes.  Please file issues as you encounter them.

**Comment by myguidingstar** [comment]
for `boot-figwheel`, use this and everything will be alright
```
[ajchemist/boot-figwheel "0.5.4-6"
                  :exclusions [figwheel-sidecar] :scope "test"]
```

**Comment by seantempesta** [comment]
Upgraded to v19.
