### ISSUE TITLE
Document basic upgrade procedure 

### ISSUE THREAD

**Issue by gmp26** [tiensonqin/exponent-cljs-template#37]
Exponent updates its sdk every month, and although this repository is usually not far behind it would be really useful if we could document the usual upgrade procedure. 

What's the basic procedure, and how to overcome the gotchas that can be encountered on the way?
I understand the necessity to update app.json and package.json, but usually find myself in dependency hell very quickly if I make any change.

I'd do it myself, but as I find it a very confusing process, I'm probably not best placed!

The need to do an update yourself arises when you want to rebase an old project on a new expo sdk because of some new sdk feature you want to use.

**Comment by seantempesta** [comment]
Honestly, I usually just do whatever the blog post recommends for normal expo upgrades.  Sometimes there's a larger change in react which affects newer versions of your rendering library (reagent or om.next), and then it's standard debugging.  My library is very similar to `re-natal`, so I also keep tabs on what they're doing.  

But yeah, good idea.  I'll add some documentation to the README.

**Comment by gmp26** [comment]
Thanks for the update. Really helpful. :)
