### ISSUE TITLE
Figwheel doesn't connect

### ISSUE THREAD

**Issue by radirk** [tiensonqin/exponent-cljs-template#5]
Thanks for the great work creating this template!
Are there additional config steps for figwheel? I run "Open on Android" in XDE and it works fine, but 
lein figwheel 
doesn't get past
Prompt will show when Figwheel connects to your application
I have all Hot Reloading etc. disabled

**Comment by radirk** [comment]
It appears I had to call the usual
adb reverse tcp:8081 tcp:8081
adb reverse tcp:3449 tcp:3449
to get the Android device to connect. It works now.
Thanks!

**Comment by prbroadfoot** [comment]
I am having the same issue but that fix did not work for me.
My physical device uses Android 4.4 which does not support `adb reverse`, so no surprise the fix didn't work there. However, I also tried it on a Genymotion emulated Android 5.1 device and it still didn't work. I see the CLJS logo + "press me" button but figwheel hangs and the only way to update the app is to restart it. Is there something else I can try?

**Comment by tiensonqin** [comment]
@prbroadfoot Could you check the content of env/dev/env/dev.cljs, 
figwheel wesocket-url will use the ip.

**Comment by prbroadfoot** [comment]
@tiensonqin Thanks! Changing the ip got it working.

**Comment by tiensonqin** [comment]
@prbroadfoot @radirk 
Hi, thank you for using this template!
I'd recommend you upgrade to the latest version, since it fixed some critical issues.
Also, If you have any problems or suggestions,
you can join Exponent slack #clojurescript channel, 
https://slack.exponentjs.com/
