### ISSUE TITLE
java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter

### ISSUE THREAD

**Issue by tasshin** [tiensonqin/exponent-cljs-template#56]
Hello,

Thanks for developing this project. I'm really excited about it!

I tried going through the steps in your README yesterday and hit a problem at the "lein figwheel" step. I've attached the output of that command here.

Michael
[output.txt](https://github.com/seantempesta/expo-cljs-template/files/1822608/output.txt)

**Comment by tirkarthi** [comment]
This occurs on JDK 9+ versions. You might want to use JDK 8 or use the `--add-modules` jvm option to add it as a separate module.

Helpful link : https://www.deps.co/blog/how-to-upgrade-clojure-projects-to-use-java-9/

**Comment by tirkarthi** [comment]
I think the right fix will be to upgrade Clojurescript version. The latest Clojurescript release 1.10 resolved the JDK 9 issue and I can see older versions being used at https://github.com/seantempesta/expo-cljs-template/blob/c907938a770828db01c92a0449a4e91c585e1339/resources/leiningen/new/expo/om/project.clj#L7 that could have caused this problem with JDK 9.

**Comment by seantempesta** [comment]
Updated and fixed!  Thanks for the advice! 

https://github.com/seantempesta/expo-cljs-template/commit/27ffbce84598b8071b6657558b1a647ec46295f5
