### ISSUE TITLE
Can't load Picker.Item

### ISSUE THREAD

**Issue by rockiger** [tiensonqin/exponent-cljs-template#57]
Hello,

I am trying to create a [Picker](https://facebook.github.io/react-native/docs/picker.html) component, but I am failing to import/load the Picker.Item class.

I use the following code with reagent at the top of my core.cljs:

```
(def picker (r/adapt-react-class (.-Picker ReactNative)))
(def picker-item (r/adapt-react-class (.-Item picker)))
```
I get the following error message: 

```
Assert failed: Component must not be nil
c
<unknown>
    figwheel-bridge.js:117:14
tryCallOne
    core.js:37:14
<unknown>
    core.js:123:25
<unknown>
    JSTimers.js:301:23
_callTimer
    JSTimers.js:154:6
_callImmediatesPass
    JSTimers.js:202:17
callImmediates
    JSTimers.js:470:11
__callImmediates
    MessageQueue.js:329:4
<unknown>
    MessageQueue.js:147:6
__guardSafe
    MessageQueue.js:316:6
flushedQueue
    MessageQueue.js:146:17
callFunctionReturnFlushedQueue
    MessageQueue.js:121:11
```

Does anybody know? What am I doing wrong?

Any help appreciated.

**Comment by seantempesta** [comment]
I think it's because you need to refer to `Picker.Item` and instead you're referring to an attribute on `Reagent's` adapted react class.  

Try:
```clojure
(def picker-item (r/adapt-react-class (.-Item (.-Picker ReactNative)))
```

**Comment by seantempesta** [comment]
@rockiger Any luck?  I'm going to close this for now, but please feel free to reopen the issue if my fix doesn't work.
