### ISSUE TITLE
asset loading for fonts and icons

### ISSUE THREAD

**Issue by gambhiro** [tiensonqin/exponent-cljs-template#58]
Have you been able to use `@expo/vector-icons` or custom fonts? I can't seem to get it working.

I posted an [issue at vector-icons](https://github.com/expo/vector-icons/issues/49) earlier, but since then I tried using a custom font and that doesn't seem to work either.

Perhaps something to do with asset loading?

I tried the Pacifico font as a local asset. In the expo cli output I see `@expo/vector-icons` being required, and `./assets/fonts/Pacifico.ttf` being required. The demo app is here:

https://github.com/gambhiro/cljs-expo-icons-demo

A snippet and a screenshot:

```
(def FontAwesome (js/require "@expo/vector-icons/FontAwesome"))
(def <fontawesome-icon> (r/adapt-react-class (aget FontAwesome "default")))

...

[text {:style {:font-size 25
              :font-family "pacifico"
              :padding-top 8
              :padding-bottom 8}}
"hey pacifico"]

[text {:style {:font-size 25
              :font-family "serif"
              :padding-top 8
              :padding-bottom 8}}
"hey serif"]

[<fontawesome-icon> {:name "camera" :size 30}]
```

![genymotion for personal use - google nexus 5x - 7 1 0 - api 25 - 1080x1920 1080x1920 420dpi - 192 168 56 101_012](https://user-images.githubusercontent.com/1586232/38481725-1aa1206c-3bc4-11e8-8888-a8c89c6353f2.png)

I installed vector-icons with yarn and in `package.json` I have:

```
    "@expo/vector-icons": "^6.3.1",
```

In `app.json` I tried

```
    "packagerOpts": {
        "assetExts": ["ttf", "otf"]
    },
    "assetBundlePatterns": [
        "assets/fonts/**",
        "assets/images/**",
        "assets/icons/**"
    ],
```

**Comment by danielneal** [comment]
I think this is related to issue #46 - I've made a PR to your demo repo that should hopefully fix it. If you try it out and it works I can make a PR to this repo to get #46 fixed.

**Comment by gambhiro** [comment]
@danielneal solved it! It is a bit obscure but not very complicated.

He says,

> I also had this problem, and realised that the Expo `registerRootComponent` does some additional work for fonts to function properly that the standard React Native `registerComponent` doesn't do. 
> 
> See these lines 
> ```https://github.com/expo/expo-sdk/blob/73d8957958546b309238a94e76836981db30911e/src/launch/registerRootComponent.js#L21-L30```
> 


https://github.com/gambhiro/cljs-expo-icons-demo/pull/1/files

@seantempesta two suggestions --

a) Would it be suitable to include these changes in the expo template?

b) Would it make sense to have a template option such as `vector-icons` and `fonts` to include a working example for those starting a new project?

Just the fix itself can be summarized as:

`figwheel-bridge.js`

``` cljs
var Expo = require('expo');

function startApp(appName, platform, devHost) {
    Expo.registerRootComponent(figwheelApp(platform, devHost));
}
```

`core.cljs`

``` cljs
(def Expo (js/require "expo"))

(defn init []
  (dispatch-sync [:initialize-db])
  (.registerRootComponent Expo (r/reactify-component app-root)))
```

![genymotion for personal use - google nexus 5x - 7 1 0 - api 25 - 1080x1920 1080x1920 420dpi - 192 168 56 101_013](https://user-images.githubusercontent.com/1586232/38504155-dac11bee-3c0b-11e8-9a22-73c82250b132.png)

**Comment by gambhiro** [comment]
@danielneal great, you already submitted the PR while I was editing :)
