### ISSUE TITLE
Can't connect to figwheel

### ISSUE THREAD

**Issue by markokocic** [tiensonqin/exponent-cljs-template#62]
I did everything like in the README, up until the point of connecting device.

I get the following error on device screen when trying to connect:
`goog.require could not find: figwheel.connect.build_main`

Did anyone make it working?

**Comment by markokocic** [comment]
OK, the error was that .lan-ip.sh script was writing wrong IP address on my system (Debian sid), so figwheel server was not working properly. When I manually put server IP address in the .lan-ip file, everything started to work.

Another thing I needed to do is to open both port 19000 and 19001 in firewall for inbound connections.

**Comment by 0atman** [comment]
This fixed it for me too. Steps to fix on ubuntu 18.04:

1. Add your lan ip manually to `.lan-ip`, ignore `lan-ip.sh`
2. `sudo ufw allow 19000/tcp`
3. `sudo ufw allow 19000/tcp`

**Comment by 0atman** [comment]
I updated the README so people will not have this friction https://github.com/seantempesta/expo-cljs-template/pull/72
