### ISSUE TITLE
consider making official releases

### ISSUE THREAD

**Issue by carocad** [tiensonqin/exponent-cljs-template#64]
I know that this is only a template and that therefore it is difficult to say what is a breaking, minor or patch release.

However the fact that there are no releases right now, leave all the users of this template in the dark whenever an update is required. 

For example,  right now I am trying to figure out how to update my template but it is pretty difficult since I dont know at which point did I use the template, so the update path is also not clear to me.

I think that having official releases would help against this since it is easy to find out the git tags of the repo and work with that.

**Comment by seantempesta** [comment]
Totally open to doing this. But I’m not sure how this would work?  I’ve been keeping the version at {expo_release}.patches. Can you even lein install an older version?

**Comment by carocad** [comment]
I dont think it is possible to install an older version. I also dont know what you are referring too with `{expo_release}.patches`; is that a file? I have not found it in the repo 😞 

My problem right now is that I used the template when the folder structure was different, and lots of  files have been modified. Since this is a template, I cannot just update my dependencies and be done with it.

I guess I would rather have one of the following options:
- a CHANGELOG (requires releases) with instructions of how to update to latest version
- an official lein pluggin that can be updated in a normal fashing (not sure if this is doable) considering the amount of glue code between JS and Cljs world.
- a simple github release tag that can be used to performs Git(hub) diffs between specific version

I think that the last option is the easiest to get going which is why I recommeded it :)

Currently what I (or everyone else for that matter) could do is perform a diff with a new generated project against the used one. This however requires only diffing the files that are relevant for the template, which can pretty tricky for people that are not that familiar with all the tricks of cljs + rn + js development.

I think that being able to perform a diff at the template level would ease things out a lot. What do you think?

**Comment by carocad** [comment]
I am closing this since it was not so difficult to do it in the end.

I simply was lacking a good tool to perform diffs of several files with several commits. In case anyone comes here I am using sourceTree quite happily for it.

Sorry for the noise
