### ISSUE TITLE
consider update template to support latest reagent version

### ISSUE THREAD

**Issue by carocad** [tiensonqin/exponent-cljs-template#68]
The re-natal project already did the job of finding a way to adapt the compiler settings and the figwheel bridge to use the latest Clojurescript require version. So now people can do

`(ns example (:require [react-native :as rn])`

It should be possible to copy/paste those changes into the expo-cljs-template but I am not sure if there were some custom adaptations that would make it not work.

Here is the PR that changed it in re-natal
https://github.com/drapanjanas/re-natal/pull/185

**Comment by gonewest818** [comment]
For what it's worth this appears to be done in commit https://github.com/seantempesta/expo-cljs-template/commit/092df401cfc76b7314499787f98fc0fe16c0cd2c, and you can require `react-native` in the `ns` form as you suggest.
