### ISSUE TITLE
Metro Bundler files Changed - Expo 31.0.0

### ISSUE THREAD

**Issue by jamesnyika** [tiensonqin/exponent-cljs-template#74]
The following has moved/changed/disappeared:

in the user.clj file there is reference to a node module path that no longer exists. 

````

....
 (defn enable-source-maps
  []
  (println "Source maps enabled.")
  (let [path "node_modules/metro/src/Server/index.js"]
    (spit path
          (str/replace (slurp path) "/\\.map$/" "/main.map$/"))))

....
````
My best guess is that is has been replaced by 

```` . 
node_modules/metro/src/server.js

````
but I am not sure. If you can give me a clue as to what this file is doing ... I can try and figure out and create a PR.. 

thanks

**Comment by seantempesta** [comment]
Well in the past they've just moved the file, but the search/replace still worked.  Have you tried running the code on the `node_modules/metro/src/server.js`?

**Comment by jamesnyika** [comment]
I have. And it resolves the exception that you would receive. I hope it does in any way lead to Issue [73](https://github.com/seantempesta/expo-cljs-template/issues/73). So when you update your Expo SDK to 31, you will need to make this change to your user.cljs file.
