### ISSUE TITLE
Add fulcro option to template.

### ISSUE THREAD

**Issue by ReilySiegel** [tiensonqin/exponent-cljs-template#75]
Is there any interest in a PR to add [Fulcro](https://fulcro.fulcrologic.com/) to the template, in addition to reagent, re-frame, and om-next? Fulcro is a fork of om-next which is slightly more opinionated. For more details on the difference between Fulcro and om-next, see [here](https://fulcro.fulcrologic.com/vsom-next.html). If there is any interest in a PR, let me know and I can get to work.

**Comment by robert-johansson** [comment]
@ReilySiegel I think it sounds very intersting! I have only heard briefly about Fulcro, but was impressed by the ideas and the work conducted.
