### ISSUE TITLE
Publish lan-ip related fix to clojars

### ISSUE THREAD

**Issue by titonbarua** [tiensonqin/exponent-cljs-template#77]
While lan-ip being improperly reported(issue #70) has been fixed in commit a5775917def3e2a4a09fef320ce6ea5e3588d836, it is yet to be published to clojars and is not available with `lein new expo` command for vast majority of users. Please fix.

Also, I came up with a `sed` based alternative, fix for issue #70, before noticing that it was already fixed. Attached here for reference:
```sh
#!/bin/bash
echo `ip route get 8.8.8.8 | sed -E "s/.*src ([0-9\.]+).*/\1/g" | awk '{print $NF; exit}'` > .lan-ip
```

**Comment by seantempesta** [comment]
Pushed (along with an update to Expo 0.34) to Clojars. [expo/lein-template "0.34.0"]
