### ISSUE TITLE
Error message on iOS+figwheel after last upgrade

### ISSUE THREAD

**Issue by robert-johansson** [tiensonqin/exponent-cljs-template#8]
When I generate a new app with `+reagent` I get the following error, ONLY on iOS+figwheel. Works great with `lein prod-build` with iOS, and always with Android.

This does also happen with the new cljs-ex-navigation example project. It dit not happen before the most recent upgrade of cljs-exponent.

<img width="487" alt="skarmavbild 2016-12-06 kl 11 05 05" src="https://cloud.githubusercontent.com/assets/8457281/20921385/1b824822-bba4-11e6-9bfe-f070d73c31d3.png">

**Comment by tiensonqin** [comment]
@robert-johansson upgrade cljs-exponent to 0.1.2 should fix this.

**Comment by robert-johansson** [comment]
@tiensonqin Yes, that worked! Thanks!
