### ISSUE TITLE
Is this template still maintained?

### ISSUE THREAD

**Issue by mfru** [tiensonqin/exponent-cljs-template#80]
There does not seem to be a lot going on here.

I came from https://docs.expo.io/versions/latest/guides/using-clojurescript/, but it seems that the template is really outdated. Is there another easy starter for developing Expo with CLJS?

**Comment by seantempesta** [comment]
Sorry @mfru.  I've been busy with other projects and am not currently working on a React Native app, so it's hard to find time to maintain this codebase.  That being said, other users seem to be having luck with a Shadow-CLJS version here:

https://github.com/PEZ/rn-rf-shadow
